apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    app: multi-containerPod
spec:
  containers:
  - name: container1
    image: httpd:latest
    ports:
    - containerPort: 80
  - name: container2
    image: busybox:latest
    command: ["sleep", "3600"]
    ports:
    - containerPort: 8080
