apiVersion: v1
kind: Pod
metadata:
  name: single-container-pod
  labels:
    app: single-container-Pod
    project_id: abc123
spec:
  containers:
  - name: container1
    image: nginx:latest
    ports:
    - containerPort: 80
