apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-server-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: sql-server-disk
    diskURI: <YOUR_AZURE_DISK_URI>
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sql-server
spec:
  replicas: 2
  serviceName: "sql-server"
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "YourStrongPassword"
        volumeMounts:
        - name: sql-server-storage
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: sql-server-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ""
      resources:
        requests:
          storage: 50Gi
