apiVersion: v1
kind: Service
metadata:
  name: svc-ws-np
spec:
  selector:
    app: webserver
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30000  # Specify the NodePort value, within range 30000-32767
  type: NodePort  # Specify the type of service